### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by notenociz** [mrmrs/profile#12]
I would like to ask for a feature: a widget that can be added onto sites to provide a better view of projects contributed to by said person.

**Use Cases:**
- projects page for personal sites
- projects list for online resumes/portfolios

**Proposed Usage Style:**
- embed much like a gist embed or codepen embed with customisable heights and widths and capability to manipulate via an API

I'm not sure what else I need to add. I just want to ask if there's anyone out there wanting this for this to be worked on.

**Comment by lachlanjc** [comment]
👍

**Comment by mrmrs** [comment]
@enociz Thanks for the ideas. Sounds like a different direction than I am looking to take this project though - but feel free to fork it and use it as a base to build that widget.

**Comment by notenociz** [comment]
That's fine. I simply wanted to know if that was something people were willing to make this into.
