### ISSUE TITLE
Really long repo names break x-width

### ISSUE THREAD

**Issue by johno** [mrmrs/profile#5]

**Comment by mrmrs** [comment]
Do you have an example of this I could test out @johnotander?

**Comment by johno** [comment]
My apologies for the vague issue, I intended to keep this as a placeholder before I submitted a PR to fix it. I guess I got sidetracked...

I can reproduce this by typing in my handle, johnotander, with a 400px viewport (on Chrome). I'm then able to scroll-x due to some additional spacing along the right. After looking into this a touch closer, it doesn't necessarily look like it is the result of long repo names, there may be something else at play.

**Comment by mrmrs** [comment]
@johnotander I think this is fixed. Let me know if it isn't on your end.
